# Generated by Django 2.1.3 on 2019-08-17 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vergi_no', models.CharField(blank=True, max_length=128, null=True, verbose_name='Vergi No')),
                ('telefon', models.CharField(max_length=120, verbose_name='Telefon Numarası')),
                ('acente_adi', models.TextField(blank=True, max_length=128, null=True, verbose_name='Acente Adi')),
                ('adres', models.TextField(blank=True, max_length=512, null=True, verbose_name='Adres')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ayar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ayar Adı')),
                ('value', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ayar Değeri')),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ayar Başlığı')),
            ],
        ),
        migrations.CreateModel(
            name='KaskoPolice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_numarasi', models.CharField(blank=True, max_length=128, null=True)),
                ('police_file', models.FileField(upload_to='uploads/kasko/%Y/%m/%d/')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='KaskoSigortasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arac_plaka', models.CharField(blank=True, max_length=50, null=True, verbose_name='Araç Plakası')),
                ('yeni_plaka', models.CharField(blank=True, max_length=50, null=True, verbose_name='Yeni Araç Plakası')),
                ('belge_seri_no', models.CharField(max_length=120, verbose_name='Belge Seri No')),
                ('kullanim_tarzi', models.CharField(max_length=128, verbose_name='Kullanım Tarzı')),
                ('arac_marka', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Araç Markası')),
                ('arac_marka_kodu', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Araç Markası Kodu')),
                ('arac_tipi', models.TextField(blank=True, null=True, verbose_name='Araç Tipi')),
                ('model_yili', models.CharField(max_length=128, null=True, verbose_name='Model Yili')),
                ('arac_faturali', models.CharField(choices=[('Evet', 'Evet'), ('Hayır', 'Hayır')], default='Hayır', max_length=128, verbose_name='Araç Faturalı mı')),
                ('fatura_tarihi', models.CharField(max_length=128, null=True, verbose_name='Fatura Tarihi')),
                ('arac_bedeli', models.CharField(blank=True, max_length=128, null=True, verbose_name='Araç Bedeli')),
                ('motor_numarasi', models.CharField(blank=True, max_length=128, null=True, verbose_name='Motor Numarası')),
                ('sasi_numarasi', models.CharField(blank=True, max_length=128, null=True, verbose_name='Saşi Numarası')),
                ('imm', models.CharField(blank=True, max_length=128, null=True, verbose_name='IMM')),
                ('koltuk_sayisi', models.CharField(blank=True, max_length=128, null=True, verbose_name='Koltuk Sayısı')),
                ('tescil_tarihi', models.CharField(max_length=128, null=True, verbose_name='Tescil Tarihi')),
                ('aksesuar_bedeli', models.CharField(blank=True, max_length=128, null=True, verbose_name='Aksesuar Bedeli')),
                ('kasa_bedeli_kasa_tipi', models.CharField(blank=True, max_length=128, null=True, verbose_name='Kasa Bedeli')),
                ('lpg_bedeli', models.CharField(blank=True, max_length=128, null=True, verbose_name='LPG Bedeli')),
                ('tasinan_emtea_ve_cinsi', models.CharField(blank=True, max_length=128, null=True, verbose_name='Taşınan Emtea ve Cinsi')),
                ('aciklama', models.TextField(blank=True, max_length=10024, null=True, verbose_name='Açıklama')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('acente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.Acente')),
            ],
        ),
        migrations.CreateModel(
            name='KrediKarti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(blank=True, max_length=512, null=True)),
                ('kart_no', models.CharField(blank=True, max_length=512, null=True)),
                ('banka', models.CharField(blank=True, max_length=512, null=True)),
                ('cv2', models.CharField(blank=True, max_length=512, null=True)),
                ('gecerlilik_tarihi', models.CharField(blank=True, max_length=512, null=True)),
                ('aciklama', models.TextField(blank=True, max_length=10000, null=True)),
                ('odeme_sekli', models.CharField(blank=True, choices=[('PEŞİN', 'PEŞİN'), ('TAKSİT', 'TAKSİT')], max_length=128, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='MenuAcente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('url', models.CharField(blank=True, max_length=120, null=True)),
                ('is_parent', models.BooleanField(default=True)),
                ('is_show', models.BooleanField(default=True)),
                ('fa_icon', models.CharField(blank=True, max_length=120, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.MenuAcente')),
            ],
        ),
        migrations.CreateModel(
            name='MenuAnaAcente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('url', models.CharField(blank=True, max_length=120, null=True)),
                ('is_parent', models.BooleanField(default=True)),
                ('is_show', models.BooleanField(default=True)),
                ('fa_icon', models.CharField(blank=True, max_length=120, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.MenuAnaAcente')),
            ],
        ),
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100, verbose_name='Adı')),
                ('soyadi', models.CharField(max_length=100, verbose_name='Soyadı')),
                ('telefon', models.CharField(max_length=120, verbose_name='Telefon Numarası')),
                ('cinsiyet', models.CharField(choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadın')], default='Kadın', max_length=128, verbose_name='Cinsiyeti')),
                ('adres', models.TextField(blank=True, max_length=512, null=True, verbose_name='Adres')),
                ('meslek', models.TextField(blank=True, null=True, verbose_name='Mesleği')),
                ('tc', models.CharField(blank=True, max_length=128, null=True, verbose_name='T.C. Kimlik Numarası')),
                ('vergi_no', models.CharField(blank=True, max_length=128, null=True, verbose_name='Vergi Numarası')),
                ('dogum_tarihi', models.DateField(null=True, verbose_name='Doğum Tarihi')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('acente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.Acente')),
            ],
        ),
        migrations.CreateModel(
            name='Odeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odeme_tutari', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('acente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.Acente')),
            ],
        ),
        migrations.CreateModel(
            name='SigortaSirketi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirket_adi', models.CharField(max_length=250, verbose_name='Şirket Adı')),
                ('aktif', models.BooleanField(blank=True, null=True, verbose_name='Etkin')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='SigortaTipi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=250, verbose_name='Şirket Adı')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='Teklif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teklif_tutari', models.DecimalField(decimal_places=2, max_digits=10)),
                ('teklif_kabul', models.BooleanField(default=False)),
                ('police_mi', models.BooleanField(default=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('prim_tutari', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('kapandi', models.BooleanField(default=False)),
                ('sigorta_sirket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.SigortaSirketi')),
            ],
        ),
        migrations.CreateModel(
            name='TeklifTalep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigorta_id', models.IntegerField(blank=True, null=True)),
                ('cevaplandi', models.BooleanField(default=False, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('acente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.Acente')),
                ('sigortaTipi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.SigortaTipi')),
                ('sigorta_Sirketleri', models.ManyToManyField(to='insurance.SigortaSirketi')),
            ],
        ),
        migrations.CreateModel(
            name='TrafikPolice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('police_numarasi', models.CharField(blank=True, max_length=128, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('teklif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.Teklif')),
            ],
        ),
        migrations.CreateModel(
            name='TrafikSigortasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arac_plaka', models.CharField(blank=True, max_length=50, null=True, verbose_name='Araç Plakası')),
                ('belge_seri_no', models.CharField(max_length=120, verbose_name='Belge Seri No')),
                ('kullanim_tarzi', models.CharField(max_length=128, verbose_name='Kullanım Tarzı')),
                ('arac_marka', models.TextField(blank=True, null=True, verbose_name='Araç Markası')),
                ('arac_tipi', models.TextField(blank=True, null=True, verbose_name='Araç Tipi')),
                ('model_yili', models.CharField(max_length=128, null=True, verbose_name='Model Yili')),
                ('arac_faturali', models.CharField(choices=[('Evet', 'Evet'), ('Hayır', 'Hayır')], default='Hayır', max_length=128, verbose_name='Araç Faturalı mı')),
                ('fatura_tarihi', models.CharField(max_length=128, null=True, verbose_name='Fatura Tarihi')),
                ('arac_bedeli', models.CharField(blank=True, max_length=128, null=True, verbose_name='Araç Bedeli')),
                ('motor_numarasi', models.CharField(blank=True, max_length=128, null=True, verbose_name='Motor Numarası')),
                ('sasi_numarasi', models.CharField(blank=True, max_length=128, null=True, verbose_name='Şasi Numarası')),
                ('imm', models.CharField(blank=True, max_length=128, null=True, verbose_name='IMM')),
                ('koltuk_sayisi', models.CharField(blank=True, max_length=128, null=True, verbose_name='Koltuk Sayısı')),
                ('tescil_tarihi', models.DateField(blank=True, null=True, verbose_name='Tescil Tarihi')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('sigortali', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.Musteri')),
            ],
        ),
        migrations.AddField(
            model_name='teklif',
            name='teklif_talep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.TeklifTalep'),
        ),
        migrations.AddField(
            model_name='kredikarti',
            name='teklif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.Teklif'),
        ),
        migrations.AddField(
            model_name='kaskosigortasi',
            name='sigortali',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.Musteri'),
        ),
        migrations.AddField(
            model_name='kaskopolice',
            name='teklif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.Teklif'),
        ),
    ]
