# Generated by Django 2.1.3 on 2019-08-06 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_auto_20190806_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='musteri',
            name='acente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.Acente'),
        ),
    ]
