from .Acente import Acente
from .KaskoSigortasi import KaskoSigortasi
from .Musteri import Musteri
from .SigortaSirketi import SigortaSirketi
from .TrafikSigortasi import TrafikSigortasi
from .Ayar import Ayar
from .SigortaTipi import SigortaTipi
from .Teklif import Teklif
from .TeklifTalep import TeklifTalep
